CREATE PROCEDURE CONFIGURE_EMAIL
@EMAIL VARCHAR(200),
@PASSWORD VARCHAR(100)
AS
BEGIN
	IF EXISTS (SELECT *FROM WorkingEmail)
		BEGIN
			UPDATE WorkingEmail SET [Email] = @EMAIL , [Password] = @PASSWORD;
		END
	ELSE
		BEGIN
			INSERT INTO WorkingEmail VALUES(@EMAIL, @PASSWORD);
		END
END