CREATE PROCEDURE [dbo].[INSERT_USER] @FNAME VARCHAR(50),@LNAME VARCHAR(50),@UNAME VARCHAR(20), @PASSWORD VARCHAR(8),@PHONENO VARCHAR(10),@EMAIL VARCHAR(50),@GENDER BIT,@CITY VARCHAR(15),@CREATEDDATE DATETIME,@CREATEDBY INT,@UPDATEDDATE DATETIME,@UPDATEDBY INT,@ROLE VARCHAR(10)
AS
BEGIN
INSERT INTO Users(FirstName, LastName, Username,[Password], ContactNo, Email, Gender, City, CreatedDate, CreatedBy, UpdatedDate, UpdatedBy, [Role])
			VALUES(@FNAME, @LNAME, @UNAME, @PASSWORD, @PHONENO, @EMAIL, @GENDER, @CITY, @CREATEDDATE, @CREATEDBY, @UPDATEDDATE, @UPDATEDBY, @ROLE)
END