CREATE PROC INSERT_CATEGORY
@COMPANY_ID INT,
@NAME VARCHAR(20),
@SHORTNAME VARCHAR(10),
@CREATEDDATE DATETIME,
@CREATEDBY  INT,
@UPDATEDDATE DATETIME,
@UPDATEDBY  INT
AS 
BEGIN
INSERT INTO Category(CompanyId, [Name], ShortName, CreatedDate, CreatedBy, UpdatedDate, Updatedby)
VALUES(@COMPANY_ID, @NAME, @SHORTNAME, @CREATEDDATE, @CREATEDBY, @UPDATEDDATE, @UPDATEDBY);
END