CREATE PROCEDURE [dbo].[INSERT_INVENTORY_RECORD] 
	@COMPANYID INT,
	@CATEGORYID INT,
	@ITEMID INT,
	@QUANTITY DECIMAL(9,2),
	@UNIT INT,
	@CREATEDDATE DATETIME,
	@CREATEDBY INT,
	@LASTUPDATED DATETIME,
	@UPDATEDBY INT,
	@MINIMUMSTOCK INT,
	@MAXIMUMSTOCK INT
AS
BEGIN
	INSERT INTO Inventory
	(
		CompanyId,
		CategoryId,
		ItemId,
		Quantity,
		Unit,
		CreatedDate,
		CreatedBy,
		LastUpdated,
		UpdatedBy,
		MinimumStock,
		MaximumStock
	)
	VALUES
	(
		@COMPANYID,
		@CATEGORYID,
		@ITEMID,
		@QUANTITY,
		@UNIT,
		@CREATEDDATE,
		@CREATEDBY,
		@LASTUPDATED,
		@UPDATEDBY,
		@MINIMUMSTOCK,
		@MAXIMUMSTOCK
	);
END;