
CREATE PROC [dbo].[INSERT_COMPANY] @NAME VARCHAR(100), @SHORTNAME VARCHAR(10), @CREATEDDATE DATETIME,@CREATEDBY INT, @UPDATEDDATE DATETIME, @UPDATEDBY INT, @ADDRESS VARCHAR(100)
AS 
BEGIN
INSERT INTO Company([Name], ShortName, CreatedDate, CreatedBy, UpdatedDate, UpdatedBy, [Address]) 
VALUES(@NAME, @SHORTNAME, @CREATEDDATE, @CREATEDBY, @UPDATEDDATE, @UPDATEDBY, @ADDRESS);
END