CREATE PROC UPDATE_STAFF_MEMBER 
	@ID INT,
	@FNAME VARCHAR(15),
	@LNAME VARCHAR(15),
	@PHONE VARCHAR(10),
	@EMAIL VARCHAR(150),
	@GENDER BIT,
	@ADDRESS VARCHAR(200),
	@DEPARTMENTID INT,
	@SALARY DECIMAL(9,0),
	@JOINDATE DATETIME,
	@LASTUPDATED DATETIME,
	@UPDATEDBY INT
AS 
BEGIN 
	UPDATE Staff SET
		[FirstName]=@FNAME,
		[LastName]=@LNAME,
		[Phone]=@PHONE,
		[Email]=@EMAIL,
		[Gender]=@GENDER,
		[Address]=@ADDRESS,
		[DepartmentId]=@DEPARTMENTID,
		[Salary]=@SALARY,
		[JoinDate]=@JOINDATE,
		[LastUpdated]=@LASTUPDATED,
		[UpdatedBy]=@UPDATEDBY
	WHERE [Id]=@ID;
END