CREATE PROC [dbo].[UPDATE_CATEGORY]
@ID INT,
@COMPANY_ID INT,
@NAME VARCHAR(20),
@SHORTNAME VARCHAR(10),
@UPDATEDDATE DATETIME,
@UPDATEDBY  INT
AS 
BEGIN
UPDATE Category SET 
CompanyId=@COMPANY_ID,
[Name] = @NAME,
ShortName = @SHORTNAME,
UpdatedDate = @UPDATEDDATE,
Updatedby = @UPDATEDBY
WHERE Id=@ID;
END