CREATE PROC [dbo].[UPDATE_INVENTORY_RECORD] 
	@ID INT,
	@COMPANYID INT,
	@CATEGORYID INT,
	@ITEMID INT,
	@QUANTITY DECIMAL,
	@UNIT INT,
	@MEASUREMENT VARCHAR(10),
	@MINIMUMSTOCK INT,
	@MAXIMUMSTOCK INT,
	@LASTUPDATED DATETIME,
	@UPDATEDBY INT
AS
BEGIN
	UPDATE Inventory SET
		CompanyId = @COMPANYID,
		CategoryId = @CATEGORYID,
		ItemId = @ITEMID,
		Quantity = @QUANTITY,
		Unit = @UNIT,
		Measurement = @MEASUREMENT,
		MinimumStock = @MINIMUMSTOCK,
		MaximumStock = @MAXIMUMSTOCK,
		LastUpdated = @LASTUPDATED,
		UpdatedBy = @UPDATEDBY
	WHERE Id = @ID;
END