CREATE PROCEDURE [dbo].[UPDATE_USER] @ID INT, @FNAME VARCHAR(50), @LNAME VARCHAR(50), @UNAME VARCHAR(20), @PASSWORD VARCHAR(8), @PHONENO VARCHAR(10), 
							 @EMAIL VARCHAR(50), @GENDER BIT, @CITY VARCHAR(15), @UPDATEDDATE DATETIME, @UPDATEDBY INT, 
							 @ROLE VARCHAR(19)
AS 
BEGIN 
UPDATE Users SET FirstName=@FNAME, LastName=@LNAME, [Username]=@UNAME, [Password]=@PASSWORD, ContactNo=@PHONENO, Email=@EMAIL, Gender=@GENDER,
				 City=@CITY, UpdatedDate=@UPDATEDDATE, UpdatedBy=@UPDATEDBY, [Role]=@ROLE WHERE Id=@ID;
END