CREATE PROC UPDATE_COMPANY 
@ID INT, 
@NAME VARCHAR(100), 
@SHORTNAME VARCHAR(10), 
@UPDATEDDATE DATETIME,
@UPDATEDBY INT,
@ADDRESS VARCHAR(100)
AS
BEGIN
UPDATE Company SET [Name]=@NAME, ShortName=@SHORTNAME, UpdatedDate=@UPDATEDDATE, UpdatedBy=@UPDATEDBY, [Address]=@ADDRESS WHERE Id=@ID;
END