CREATE PROC UPDATE_DEPARTMENT
	@ID INT,
	@NAME VARCHAR(50),
	@SHORTNAME VARCHAR(10),
	@PHONE VARCHAR(10),
	@DESCRIPTION TEXT,
	@LASTUPDATED DATETIME,
	@UPDATEDBY INT
AS
BEGIN
	UPDATE Department SET
		[Name]=@NAME,
		[ShortName]=@SHORTNAME,
		[Phone]=@PHONE,
		[Description]=@DESCRIPTION,
		[LastUpdated]=@LASTUPDATED,
		[UpdatedBy]=@UPDATEDBY
	WHERE [Id]=@ID;
END